### ISSUE TITLE
Starting the client password is asked ??

### ISSUE THREAD

**Issue by rickvek** [DesktopContainers/icaclient#13]
docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
37d1369b16bd        mwaeckerlin/icaclient   "/bin/sh -c 'echo ..."   5 weeks ago         Up 7 minutes                            icaclient

ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
> -X app@$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' icaclient)
Warning: Permanently added '172.17.0.2' (ECDSA) to the list of known hosts.
app@172.17.0.2's password:

**Comment by MarvAmBass** [comment]
Hi there, that's interessting - it's configured to work without password
so I didn't configure one in the first place.

unfortunately I'm not able to test it since I don't have a system to check this.

you can either set a password for the user app inside the container `docker exec -ti <containernid> bash`
or import your ssh key for the user app - docker copy and docker exec

I'll take a look as soon as it;s possible but it will take a few weeks I guess

**Comment by PibePlayer** [comment]
> 

I'm having the same problem

**Comment by MarvAmBass** [comment]
@all hi there, it seems that sometimes even the host system has tight ssh security settings, so that it will not allow empty passwords. you can always use the http mode of this container and work in a webvnc session
